runtime: nodejs18

handlers:
- url: /src/styles
  static_dir: src/styles

- url: /src/scripts
  static_dir: src/scripts

- url: /src/images
  static_dir: src/images

- url: /favicon.png
  static_files: favicon.png
  upload: favicon.png

- url: /
  static_files: index.html
  upload: index.html